In [1]:
import pandas as pd
import numpy as np

In [2]:
pdf = pd.read_csv("polls.csv")

In [3]:
pdf.shape

(12624, 27)

In [4]:
pdf.head(5)

,cycle,branch,type,matchup,forecastdate,state,startdate,enddate,pollster,grade,...,adjpoll_clinton,adjpoll_trump,adjpoll_johnson,adjpoll_mcmullin,multiversions,url,poll_id,question_id,createddate,timestamp
0,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/3/2016,11/6/2016,ABC News/Washington Post,A+,...,45.20163,41.72430,4.626221,NaN,NaN,https://www.washingtonpost.com/news/the-fix/wp...,48630,76192,11/7/16,09:35:33 8 Nov 2016
1,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/1/2016,11/7/2016,Google Consumer Surveys,B,...,43.34557,41.21439,5.175792,NaN,NaN,https://datastudio.google.com/u/0/#/org//repor...,48847,76443,11/7/16,09:35:33 8 Nov 2016
2,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/2/2016,11/6/2016,Ipsos,A-,...,42.02638,38.81620,6.844734,NaN,NaN,http://projects.fivethirtyeight.com/polls/2016...,48922,76636,11/8/16,09:35:33 8 Nov 2016
3,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/4/2016,11/7/2016,YouGov,B,...,45.65676,40.92004,6.069454,NaN,NaN,https://d25d2506sfb94s.cloudfront.net/cumulus_...,48687,76262,11/7/16,09:35:33 8 Nov 2016
4,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/3/2016,11/6/2016,Gravis Marketing,B-,...,46.84089,42.33184,3.726098,NaN,NaN,http://www.gravispolls.com/2016/11/final-natio...,48848,76444,11/7/16,09:35:33 8 Nov 2016

In [5]:
pdf.columns

Index(['cycle', 'branch', 'type', 'matchup', 'forecastdate', 'state',
       'startdate', 'enddate', 'pollster', 'grade', 'samplesize', 'population',
       'poll_wt', 'rawpoll_clinton', 'rawpoll_trump', 'rawpoll_johnson',
       'rawpoll_mcmullin', 'adjpoll_clinton', 'adjpoll_trump',
       'adjpoll_johnson', 'adjpoll_mcmullin', 'multiversions', 'url',
       'poll_id', 'question_id', 'createddate', 'timestamp'],
      dtype='object')

### i) checking whether any columns can be dropped, as there are 27 of them.

In [6]:
pdf.cycle.unique()

# contains only one unique value thus can be dropped.

array([2016], dtype=int64)

In [7]:
pdf["branch"].unique()

array(['President'], dtype=object)

##### ["cycle","branch","url","poll_id","question_id",] can be dropped.

In [8]:
# checking which of the columns have just 1 unique value, possible candidate for dropping.
can_be_dropped = []
print("These columns can be dropped: \n")
for col in pdf.columns:
    if  len(pdf[col].unique()) == 1:
        can_be_dropped.append(col)
print(can_be_dropped)

These columns can be dropped:

['cycle', 'branch', 'matchup', 'forecastdate']

In [9]:
pdf.nunique()

cycle                   1
branch                  1
type                    3
matchup                 1
forecastdate            1
state                  57
startdate             352
enddate               345
pollster              196
grade                  10
samplesize           1766
population              4
poll_wt              4399
rawpoll_clinton      1312
rawpoll_trump        1385
rawpoll_johnson       584
rawpoll_mcmullin       16
adjpoll_clinton     12569
adjpoll_trump       12582
adjpoll_johnson      6629
adjpoll_mcmullin       57
multiversions           1
url                  1304
poll_id              4208
question_id          4208
createddate           222
timestamp               3
dtype: int64

In [10]:
for col in pdf.columns:
    print(f"for column named {col} these are the unique values:")
    print(pdf[col].unique())
    print("\n")

for column named cycle these are the unique values:
[2016]


for column named branch these are the unique values:
['President']


for column named type these are the unique values:
['polls-plus' 'now-cast' 'polls-only']


for column named matchup these are the unique values:
['Clinton vs. Trump vs. Johnson']


for column named forecastdate these are the unique values:
['11/8/16']


for column named state these are the unique values:
['U.S.' 'New Mexico' 'Virginia' 'Iowa' 'Wisconsin' 'North Carolina'
 'Georgia' 'Florida' 'Oregon' 'Ohio' 'South Carolina' 'New York'
 'Michigan' 'Pennsylvania' 'Missouri' 'New Hampshire' 'Arizona' 'Nevada'
 'Colorado' 'California' 'Washington' 'Texas' 'Utah' 'Illinois' 'Indiana'
 'Tennessee' 'Connecticut' 'Massachusetts' 'New Jersey' 'Kansas'
 'Kentucky' 'Minnesota' 'Oklahoma' 'Maryland' 'Alabama' 'Nebraska'
 'Louisiana' 'Maine' 'Arkansas' 'Alaska' 'Vermont' 'Idaho' 'Mississippi'
 'West Virginia' 'South Dakota' 'Montana' 'Hawaii' 'Maine CD-1'
 'Maine CD-2' 'Rhode Island' 'Nebraska CD-3' 'Nebraska CD-1' 'Delaware'
 'North Dakota' 'District of Columbia' 'Nebraska CD-2' 'Wyoming']


for column named startdate these are the unique values:
['11/3/2016' '11/1/2016' '11/2/2016' '11/4/2016' '11/6/2016' '11/5/2016'
 '10/26/2016' '10/27/2016' '10/31/2016' '10/20/2016' '10/25/2016'
 '10/30/2016' '10/22/2016' '10/28/2016' '10/29/2016' '10/21/2016'
 '10/23/2016' '10/14/2016' '10/17/2016' '10/24/2016' '10/16/2016'
 '10/18/2016' '10/19/2016' '10/11/2016' '10/12/2016' '10/10/2016'
 '10/7/2016' '9/25/2016' '10/13/2016' '10/8/2016' '10/15/2016' '9/29/2016'
 '10/3/2016' '10/5/2016' '10/6/2016' '10/9/2016' '10/4/2016' '9/27/2016'
 '9/21/2016' '10/1/2016' '9/1/2016' '9/19/2016' '9/28/2016' '10/2/2016'
 '9/26/2016' '9/20/2016' '9/30/2016' '9/22/2016' '9/23/2016' '9/18/2016'
 '9/16/2016' '9/9/2016' '9/15/2016' '9/4/2016' '9/17/2016' '9/24/2016'
 '9/13/2016' '9/11/2016' '9/12/2016' '9/2/2016' '9/6/2016' '9/10/2016'
 '8/30/2016' '8/22/2016' '9/14/2016' '9/7/2016' '9/8/2016' '8/21/2016'
 '8/26/2016' '9/3/2016' '8/28/2016' '8/19/2016' '8/18/2016' '8/29/2016'
 '8/15/2016' '8/17/2016' '8/25/2016' '8/27/2016' '8/23/2016' '9/5/2016'
 '8/12/2016' '8/20/2016' '8/31/2016' '8/24/2016' '8/9/2016' '8/4/2016'
 '8/11/2016' '8/13/2016' '8/16/2016' '8/3/2016' '7/19/2016' '8/8/2016'
 '7/20/2016' '8/7/2016' '7/13/2016' '8/10/2016' '8/5/2016' '8/1/2016'
 '7/29/2016' '7/9/2016' '7/5/2016' '7/7/2016' '7/6/2016' '7/31/2016'
 '8/14/2016' '7/11/2016' '8/2/2016' '7/26/2016' '7/8/2016' '7/25/2016'
 '6/30/2016' '7/14/2016' '7/21/2016' '7/23/2016' '8/6/2016' '6/26/2016'
 '7/18/2016' '6/8/2016' '6/1/2016' '5/29/2016' '6/15/2016' '6/22/2016'
 '6/19/2016' '6/10/2016' '7/22/2016' '6/13/2016' '6/14/2016' '5/31/2016'
 '7/30/2016' '7/12/2016' '6/21/2016' '6/7/2016' '7/27/2016' '5/10/2016'
 '5/26/2016' '5/23/2016' '6/11/2016' '6/24/2016' '6/23/2016' '6/4/2016'
 '5/27/2016' '4/26/2016' '6/25/2016' '7/1/2016' '6/16/2016' '5/25/2016'
 '5/18/2016' '6/27/2016' '7/17/2016' '5/16/2016' '6/9/2016' '4/25/2016'
 '4/29/2016' '6/5/2016' '5/19/2016' '5/12/2016' '5/11/2016' '5/24/2016'
 '4/5/2016' '6/20/2016' '5/2/2016' '4/15/2016' '4/4/2016' '7/28/2016'
 '5/21/2016' '5/13/2016' '4/7/2016' '6/28/2016' '7/24/2016' '3/28/2016'
 '5/6/2016' '4/6/2016' '6/17/2016' '3/30/2016' '3/31/2016' '3/4/2016'
 '4/12/2016' '4/10/2016' '4/11/2016' '5/9/2016' '3/23/2016' '5/15/2016'
 '3/22/2016' '4/1/2016' '5/5/2016' '4/18/2016' '3/1/2016' '6/2/2016'
 '5/14/2016' '4/20/2016' '4/17/2016' '3/29/2016' '3/7/2016' '5/17/2016'
 '4/28/2016' '3/19/2016' '3/17/2016' '2/21/2016' '7/16/2016' '7/15/2016'
 '7/10/2016' '4/22/2016' '4/23/2016' '3/3/2016' '7/4/2016' '7/3/2016'
 '3/20/2016' '3/16/2016' '7/2/2016' '4/8/2016' '3/14/2016' '6/29/2016'
 '3/2/2016' '2/11/2016' '2/26/2016' '6/18/2016' '3/24/2016' '2/5/2016'
 '2/22/2016' '4/19/2016' '1/30/2016' '6/12/2016' '1/9/2016' '3/13/2016'
 '6/6/2016' '1/18/2016' '5/30/2016' '2/15/2016' '2/24/2016' '5/28/2016'
 '3/21/2016' '2/18/2016' '1/8/2016' '5/22/2016' '3/18/2016' '5/20/2016'
 '2/4/2016' '2/10/2016' '2/19/2016' '2/3/2016' '2/2/2016' '2/14/2016'
 '1/12/2016' '12/4/2015' '5/8/2016' '5/7/2016' '6/3/2016' '5/4/2016'
 '5/3/2016' '1/5/2016' '1/15/2016' '11/15/2015' '5/1/2016' '4/27/2016'
 '4/24/2016' '4/30/2016' '12/17/2015' '11/10/2015' '1/21/2016' '4/21/2016'
 '4/16/2016' '11/16/2015' '4/14/2016' '11/6/2015' '4/13/2016' '11/7/2015'
 '4/9/2016' '1/4/2016' '4/3/2016' '4/2/2016' '3/27/2016' '12/10/2015'
 '3/26/2016' '3/25/2016' '12/16/2015' '12/2/2015' '3/15/2016' '3/12/2016'
 '3/11/2016' '12/6/2015' '1/19/2016' '3/10/2016' '3/9/2016' '3/8/2016'
 '3/6/2016' '3/5/2016' '2/29/2016' '11/27/2015' '11/23/2015' '11/29/2015'
 '2/28/2016' '2/25/2016' '2/27/2016' '2/23/2016' '2/17/2016' '2/20/2016'
 '2/16/2016' '11/9/2015' '2/13/2016' '2/12/2016' '2/9/2016' '2/8/2016'
 '2/7/2016' '2/6/2016' '1/10/2016' '1/29/2016' '2/1/2016' '1/31/2016'
 '1/28/2016' '1/27/2016' '1/26/2016' '1/25/2016' '1/24/2016' '1/23/2016'
 '1/22/2016' '1/20/2016' '1/17/2016' '1/14/2016' '1/16/2016' '1/13/2016'
 '1/11/2016' '12/22/2015' '1/7/2016' '1/3/2016' '1/6/2016' '1/2/2016'
 '1/1/2016' '12/7/2015' '12/26/2015' '12/27/2015' '12/25/2015'
 '12/31/2015' '12/24/2015' '12/23/2015' '12/21/2015' '12/30/2015'
 '12/20/2015' '12/19/2015' '12/18/2015' '12/11/2015' '12/29/2015'
 '12/15/2015' '12/14/2015' '12/28/2015' '12/3/2015' '12/13/2015'
 '11/13/2015' '11/11/2015' '11/30/2015' '11/12/2015' '12/8/2015'
 '12/5/2015']


for column named enddate these are the unique values:
['11/6/2016' '11/7/2016' '11/5/2016' '11/4/2016' '11/3/2016' '10/31/2016'
 '10/30/2016' '11/2/2016' '11/1/2016' '10/25/2016' '10/24/2016'
 '10/26/2016' '10/27/2016' '10/28/2016' '10/23/2016' '10/29/2016'
 '10/22/2016' '10/18/2016' '10/21/2016' '10/17/2016' '10/20/2016'
 '10/19/2016' '10/14/2016' '10/12/2016' '10/16/2016' '10/11/2016'
 '9/26/2016' '10/15/2016' '10/13/2016' '10/10/2016' '10/2/2016'
 '10/6/2016' '10/7/2016' '9/30/2016' '10/8/2016' '9/29/2016' '9/23/2016'
 '10/5/2016' '10/4/2016' '9/27/2016' '9/25/2016' '10/9/2016' '9/24/2016'
 '10/3/2016' '10/1/2016' '9/20/2016' '9/28/2016' '9/12/2016' '9/10/2016'
 '9/21/2016' '9/19/2016' '9/17/2016' '9/22/2016' '9/13/2016' '9/18/2016'
 '9/14/2016' '9/5/2016' '8/31/2016' '8/23/2016' '9/8/2016' '9/11/2016'
 '8/28/2016' '8/30/2016' '8/21/2016' '9/15/2016' '9/1/2016' '9/7/2016'
 '9/16/2016' '8/19/2016' '8/27/2016' '8/29/2016' '9/9/2016' '9/2/2016'
 '8/14/2016' '8/24/2016' '8/22/2016' '9/4/2016' '8/10/2016' '8/11/2016'
 '8/16/2016' '8/8/2016' '9/6/2016' '8/7/2016' '8/13/2016' '8/15/2016'
 '7/19/2016' '7/24/2016' '8/17/2016' '7/17/2016' '8/12/2016' '8/4/2016'
 '7/15/2016' '8/3/2016' '8/1/2016' '7/12/2016' '7/11/2016' '7/10/2016'
 '7/29/2016' '7/8/2016' '7/31/2016' '8/18/2016' '7/23/2016' '8/5/2016'
 '7/27/2016' '7/21/2016' '7/16/2016' '8/9/2016' '7/13/2016' '7/9/2016'
 '8/20/2016' '7/6/2016' '6/29/2016' '7/18/2016' '7/20/2016' '7/26/2016'
 '7/2/2016' '6/28/2016' '6/5/2016' '5/31/2016' '6/20/2016' '6/24/2016'
 '7/14/2016' '6/22/2016' '6/14/2016' '6/15/2016' '6/23/2016' '6/3/2016'
 '6/21/2016' '7/30/2016' '6/26/2016' '6/8/2016' '6/18/2016' '6/7/2016'
 '5/16/2016' '7/22/2016' '6/19/2016' '7/25/2016' '5/27/2016' '6/13/2016'
 '7/7/2016' '6/27/2016' '6/6/2016' '5/30/2016' '8/2/2016' '4/28/2016'
 '7/5/2016' '5/28/2016' '5/22/2016' '5/19/2016' '8/25/2016' '6/10/2016'
 '5/11/2016' '5/1/2016' '5/15/2016' '5/12/2016' '5/24/2016' '6/2/2016'
 '4/9/2016' '9/3/2016' '5/4/2016' '4/17/2016' '4/7/2016' '8/26/2016'
 '5/5/2016' '5/23/2016' '8/6/2016' '5/25/2016' '6/16/2016' '4/10/2016'
 '3/30/2016' '5/9/2016' '4/27/2016' '5/26/2016' '4/3/2016' '4/11/2016'
 '5/13/2016' '3/10/2016' '4/15/2016' '4/16/2016' '6/4/2016' '3/24/2016'
 '3/29/2016' '5/6/2016' '4/8/2016' '4/21/2016' '3/3/2016' '5/17/2016'
 '4/24/2016' '4/20/2016' '3/31/2016' '3/11/2016' '5/18/2016' '3/22/2016'
 '7/28/2016' '2/22/2016' '3/20/2016' '5/20/2016' '4/25/2016' '4/14/2016'
 '3/23/2016' '4/19/2016' '7/4/2016' '7/3/2016' '3/6/2016' '7/1/2016'
 '4/13/2016' '3/2/2016' '4/12/2016' '6/30/2016' '3/16/2016' '2/16/2016'
 '2/29/2016' '6/25/2016' '3/21/2016' '3/26/2016' '2/7/2016' '4/2/2016'
 '2/23/2016' '2/6/2016' '6/17/2016' '2/20/2016' '1/9/2016' '6/12/2016'
 '6/11/2016' '3/17/2016' '2/27/2016' '1/20/2016' '2/19/2016' '2/28/2016'
 '6/1/2016' '6/9/2016' '2/15/2016' '5/29/2016' '1/10/2016' '5/21/2016'
 '2/26/2016' '2/5/2016' '2/4/2016' '1/12/2016' '5/14/2016' '2/17/2016'
 '12/9/2015' '5/10/2016' '2/3/2016' '5/8/2016' '5/7/2016' '1/18/2016'
 '11/17/2015' '4/29/2016' '4/30/2016' '5/3/2016' '5/2/2016' '3/4/2016'
 '4/26/2016' '12/20/2015' '11/16/2015' '1/24/2016' '4/23/2016' '12/2/2015'
 '4/22/2016' '11/23/2015' '1/26/2016' '4/18/2016' '11/8/2015' '1/13/2016'
 '1/7/2016' '4/6/2016' '4/1/2016' '4/4/2016' '4/5/2016' '12/13/2015'
 '3/28/2016' '12/21/2015' '3/27/2016' '12/17/2015' '12/6/2015' '3/25/2016'
 '3/19/2016' '3/18/2016' '3/15/2016' '3/14/2016' '3/13/2016' '3/12/2016'
 '3/9/2016' '3/8/2016' '3/1/2016' '12/1/2015' '11/30/2015' '3/7/2016'
 '3/5/2016' '12/3/2015' '2/25/2016' '2/21/2016' '2/24/2016' '11/19/2015'
 '2/18/2016' '11/13/2015' '2/14/2016' '2/13/2016' '2/12/2016' '2/11/2016'
 '2/10/2016' '2/9/2016' '2/8/2016' '2/2/2016' '2/1/2016' '1/31/2016'
 '1/30/2016' '1/29/2016' '1/28/2016' '1/27/2016' '1/25/2016' '1/23/2016'
 '1/22/2016' '1/21/2016' '1/17/2016' '1/19/2016' '1/16/2016' '1/15/2016'
 '1/14/2016' '12/23/2015' '1/11/2016' '1/8/2016' '1/6/2016' '1/5/2016'
 '12/8/2015' '12/30/2015' '12/31/2015' '12/29/2015' '1/4/2016'
 '12/28/2015' '12/27/2015' '12/26/2015' '12/25/2015' '1/3/2016'
 '12/24/2015' '12/22/2015' '12/15/2015' '1/2/2016' '12/19/2015'
 '12/18/2015' '1/1/2016' '12/7/2015' '11/15/2015' '12/14/2015']


for column named pollster these are the unique values:
['ABC News/Washington Post' 'Google Consumer Surveys' 'Ipsos' 'YouGov'
 'Gravis Marketing'
 'Fox News/Anderson Robbins Research/Shaw & Company Research'
 'CBS News/New York Times' 'NBC News/Wall Street Journal' 'Zia Poll'
 'IBD/TIPP' 'Selzer & Company' 'Angus Reid Global' 'Monmouth University'
 'Public Policy Polling' 'Marist College' 'The Times-Picayune/Lucid'
 'Marquette University' 'Siena College' 'Landmark Communications'
 'Quinnipiac University' 'USC Dornsife/LA Times'
 'RKM Research and Communications, Inc.' 'Remington'
 'Christopher Newport University' 'Emerson College' 'CVOTER International'
 'Morning Consult' 'SurveyMonkey' 'Clarity Campaign Labs'
 'University of New Hampshire' 'Pew Research Center' 'SurveyUSA'
 'Rasmussen Reports/Pulse Opinion Research'
 'Greenberg Quinlan Rosner/American Viewpoint' 'Saguaro Strategies'
 'Hampton University' 'Insights West' 'CNN/Opinion Research Corp.'
 'Trafalgar Group' 'RAND (American Life Panel)' 'RABA Research'
 'GfK Group' 'EPIC-MRA' 'BK Strategies'
 'Public Policy Institute of California' 'Columbus Dispatch'
 'Keating Research, Inc.' 'Opinion Savvy/InsiderAdvantage'
 'Research & Polling, Inc.' 'University of Massachusetts Lowell'
 'TargetSmart/William & Mary' 'Public Opinion Strategies'
 'Susquehanna Polling & Research, Inc.' 'Stockton College'
 'Winthrop University' 'Franklin & Marshall College' 'Dixie Strategies'
 'University of North Florida' 'Data Orbital' 'Cygnal Political'
 'Suffolk University' 'MassINC Polling Group' 'Muhlenberg College'
 'Political Marketing International, Inc./Red Racing Horses'
 'Starboard Communications' 'Harper Polling'
 'Mitchell Research & Communications' 'Elon University'
 'Strategic National' 'Time/Abt SRBI' 'Loras College'
 'American Research Group' 'Roanoke College'
 'Mason-Dixon Polling & Research, Inc.'
 'Greenberg Quinlan Rosner (Democracy Corps)' 'University of Denver'
 'Y2 Analytics' 'Saint Leo University' 'DFM Research' 'Victory Research'
 'Magellan Strategies' 'University of Arkansas' 'JMC Enterprises'
 'Bendixen & Amandi International' 'Davis, Hibbitts & Midghall, Inc.'
 'Associated Industries of Florida' 'Western Kentucky University'
 'Crosswind Media & Public Relations' 'Dan Jones & Associates'
 'Western New England University' 'Elway Research'
 'Princeton Survey Research Associates International'
 "Maine People's Resource Center" 'St. Norbert College' 'Braun Research'
 'University of Houston' 'Centre College'
 'Public Religion Research Institute' 'National Research, Inc.'
 'SoonerPoll.com' 'Praecones Analytica' 'Nielson Brothers Polling'
 'George Washington University (Battleground)'
 'North Star Opinion Research/Ayres, McHenry & Associates'
 'Southern Media & Opinion Research' 'Craciun Research'
 'Fort Hays State University' 'University of Colorado'
 'Florida Atlantic University' 'Marketing Resource Group (MRG)'
 'Hendrix College' 'Baldwin Wallace University'
 'University of New Orleans' 'McLaughlin & Associates' 'Tarrance Group'
 'Arizona State University' 'Global Strategy Group'
 'Riley Research Associates' 'Ball State University'
 'Lake Research Partners' 'Illinois Public Opinion Strategies'
 'University of Wyoming' 'Cherry Communications' 'Glengariff Group, Inc.'
 'Castleton University' 'Southern Illinois University'
 'Clout Research/Wenzel Strategies' 'University of Akron' 'icitizen'
 'Sacramento State' 'HighGround' 'Edison Research'
 'Michigan State University' 'Garin-Hart-Yang Research Group'
 'Fairleigh Dickinson University (PublicMind)' 'Vanderbilt University'
 'Moore Information' 'High Point University' 'Market Research Insight'
 'Echelon Insights' 'Normington, Petts & Associates'
 'Hoffman Research Group' 'Strategies 360' 'MBQF'
 'Montana State University Billings' 'Anzalone Liszt Grove Research'
 'GBA Strategies' 'Middle Tennessee State University'
 'University of Delaware' 'Ivan Moore Research' 'Goucher College'
 'Meredith College' 'Target Insyght' 'University of Mary Washington'
 'Mercyhurst University' 'We Ask America' 'Rutgers University'
 'Just Win Strategies' 'Texas Lyceum' 'First Tuesday Strategies'
 'OpinionWorks' 'Utah Valley University' 'Tulchin Research'
 'Feldman Group' 'R.L. Repass & Partners' 'Zogby Interactive/JZ Analytics'
 'Strategy Research' 'Vox Populi Communications' 'Expedition Strategies'
 'Penn Schoen Berland' 'Integrated Web Strategy' 'Basswood Research'
 'Fairbank, Maslin, Maullin, Metz & Associates'
 'Field Research Corporation (Field Poll)' 'OnMessage Inc.'
 'Hickman Analytics' 'American Strategies' 'National Journal'
 'Evolving Strategies' 'Leland Beatty' 'TargetPoint'
 'Political Callers, Inc.' 'Schoen Consulting' 'Data Targeting'
 'Bellwether Research & Consulting' 'Cole Hargrave Snodgrass & Associates'
 'Baruch College' 'Behavior Research Center (Rocky Mountain)'
 'Harvard University' 'Dartmouth College' 'Merrill Poll'
 'Critical Insights' 'Orion Strategies' 'Robert Morris University'
 'Florida Southern College' 'Ogden & Fry']


for column named grade these are the unique values:
['A+' 'B' 'A-' 'B-' 'A' nan 'B+' 'C+' 'C-' 'C' 'D']


for column named samplesize these are the unique values:
[ 2220. 26574.  2195. ...  2422.  1576.   950.]


for column named population these are the unique values:
['lv' 'rv' 'a' 'v']


for column named poll_wt these are the unique values:
[8.720654e+00 7.628472e+00 6.424334e+00 ... 1.460000e-06 1.374718e-01
 1.013230e-02]


for column named rawpoll_clinton these are the unique values:
[47.   38.03 42.   ... 46.54 21.33 46.46]


for column named rawpoll_trump these are the unique values:
[43.   35.69 39.   ... 40.04 35.05 37.41]


for column named rawpoll_johnson these are the unique values:
[ 4.    5.46  6.    5.    3.    7.1   1.    2.     nan  4.3   4.5   8.
  6.8   7.    9.    6.6  10.   11.    1.89  2.89  7.7   2.43  3.89  2.3
  3.9   2.58  4.9   5.04  2.96  3.59  5.4   2.6  16.    3.2   7.6   4.95
  5.6  22.    4.2   6.3  12.    6.22  4.56  3.53  5.31  5.36  4.89  4.4
  8.9   3.33  4.03  4.8   6.42  5.15  7.26  6.55  2.7   8.4   5.97  5.88
  6.47  3.5   5.12  9.5   5.57  4.48  4.04  3.98  4.14  3.21  6.5   5.82
  5.8   7.04 10.3   4.7   4.15  5.2   1.9   2.54  5.3   4.73  8.84  6.87
  8.3   3.8   2.9   3.4   3.3   5.5   4.6   6.1   6.71 14.    3.6   4.94
  8.1  13.    3.7   6.2   6.79  7.3   5.1   3.36 11.4   8.5   6.67  5.9
  2.39  5.7   8.8   2.17  6.7   6.61  4.1  17.9   9.43  7.9  24.   10.7
  5.99  4.72  2.2   1.32  7.8   4.05  6.4   8.2  15.    4.78  4.23 10.86
  6.13  8.7  10.4   2.77  5.48 14.47  2.68  8.01  6.18  9.73  5.54  8.32
  4.12  8.88  7.5   1.93  4.54  6.35  3.51  6.19  6.17  4.07  9.3   3.79
  6.69  2.8   9.9   9.38  5.87  6.92 10.06  3.86  7.21  6.59  6.23  9.8
  7.4   5.73  5.27  7.19  5.29  7.45  7.53  7.74  8.95  7.57  6.46 10.35
  9.51  7.16  4.27  6.66  5.21  3.37  7.94  6.9   8.99  7.51 19.    7.41
  6.56 11.78  6.36  6.51  9.09  4.59  4.87  7.2   5.64  9.2   3.81 12.04
  5.53  8.71 12.1   9.4  17.    7.31  6.97  3.12  6.31  5.45 10.11  5.74
  6.37  2.15  3.14  5.66 18.    9.31 10.1  16.91  8.21 13.27 11.55  3.97
  8.11  8.85  7.47  7.69  5.86  6.06  6.39  5.85  1.81  4.76 20.   11.46
  9.15  7.17 10.23 11.1   1.49  3.69  5.07  3.64  5.83  6.33  6.75  8.63
  6.21  7.46  9.22  2.26 12.22  5.19  5.26  7.98 13.84  6.96  6.49 10.78
  9.55  6.04  7.33  4.88 14.35  6.24  5.41  5.11  4.55  5.71  8.34 13.99
  6.91  8.59 14.3   6.52  7.64  7.62  7.37  8.15 17.1  10.5   3.71  9.66
  5.14  4.57  7.18  7.82  3.77  4.65  6.99  2.85 10.26 21.    8.61  6.62
  7.85  6.88  8.09  2.05  6.65  5.62  2.51  5.25 10.98  5.49  7.23  7.01
 14.56 11.85  7.76  2.74  5.17 16.1   9.39 10.8   6.01  4.46 11.42  7.81
  7.58  8.17  6.68  7.75  9.7   4.64  7.56  4.17 10.83  5.24  6.54  0.
 14.54  7.77 11.77 11.86 17.14 12.39  9.92  4.84  7.24  6.76 11.6   3.96
  5.78 12.73  4.92  7.83  9.94  9.59 10.02  7.66  6.43  3.91  9.23  7.12
  6.48  3.58  6.95  6.86  9.04 12.96  3.99 10.38 25.   10.64  7.02  4.68
  5.33  4.93  6.32  7.39 13.38  5.16 12.95  8.53 17.4   5.03  4.38  5.77
  7.28 13.28  8.91 14.78  8.49  7.03 10.44  9.46  8.26  4.85  2.79  9.21
  7.86  4.33  8.46 14.24  6.93  8.14  7.61 15.06  7.91  5.61  5.65 10.58
  9.37  9.48  5.09  4.86  8.96  6.77  4.98  8.68  7.68 12.98  8.45  0.98
  6.94  8.44  6.08 17.29 15.6   5.93 12.97  7.07  6.07  8.06 10.22  9.14
  7.92  8.74  9.78  6.82  4.69  7.79 11.39 14.61 10.52 12.76  9.98 15.58
 14.66 10.73 12.52  7.93  8.18  8.35  6.85  9.18  5.52 13.01  8.57  8.86
  5.67 11.35  9.61  8.75  8.69  6.15 10.43  9.36  9.49  9.91  8.51 10.37
 11.65 15.04  9.47 11.18  9.42 12.7   5.91  6.38 12.2  18.44 10.36  8.12
 15.45 10.63  9.96  4.77  5.89 10.42 12.02  8.52  8.39 12.77 13.39  8.64
 11.13  8.87 10.2   8.07  7.08  5.47  7.73  6.34  6.05 11.37 12.78  9.74
 14.71  9.24 10.88 11.5   9.34 10.59 16.45  8.76  8.23  7.78 11.43  7.88
  9.84  9.75  9.33  9.81 11.97 10.51  9.86 11.95  8.54  8.48  7.13  7.44
  3.31 10.15  8.31 11.3  19.84  8.72 10.74 15.11 12.84  9.06  9.6  11.48
  8.62  8.19 12.88  9.77  8.79  8.92  9.12  7.65  9.69 12.32 20.47  6.98
  7.87 11.12  7.42  8.24  5.69  8.47  8.22  9.62 10.55  7.48 12.4   9.02
  6.57 12.19  8.66 10.97 10.27  7.36  7.63  9.83 13.75 10.92 16.75 13.26
 11.45 12.93 15.32 14.51  8.38 12.3  23.   10.89  9.99]


for column named rawpoll_mcmullin these are the unique values:
[  nan 24.   27.6  24.52 25.   21.   28.   30.   20.   29.   31.   18.
 22.    9.   12.   27.   26.  ]


for column named adjpoll_clinton these are the unique values:
[45.20163 43.34557 42.02638 ... 53.83622 49.57558 46.40999]


for column named adjpoll_trump these are the unique values:
[41.7243  41.21439 38.8162  ... 32.47939 39.96954 39.19839]


for column named adjpoll_johnson these are the unique values:
[4.626221 5.175792 6.844734 ... 3.904715 6.92411  3.881193]


for column named adjpoll_mcmullin these are the unique values:
[     nan 24.      27.70142 24.13522 24.52    25.      24.10142 21.16903
 28.06761 30.37186 20.81133 20.74372 29.37186 31.57469 18.87894 25.03381
 29.67611 22.81133 29.6423  11.5692  13.65646 25.10142 27.37186 26.13522
 25.16903 11.02832 26.20283 26.23664 29.43947 26.27044 29.47327 27.70303
 24.13737 24.10303 21.17171 28.06868 30.37776 20.8242  20.75552 29.37776
 31.58381 18.89288 25.03434 29.68683 22.8242  29.65249 11.60996 13.68274

In [11]:
# using a method
pdf.apply(pd.unique)

cycle                                                          [2016]
branch                                                    [President]
type                               [polls-plus, now-cast, polls-only]
matchup                               [Clinton vs. Trump vs. Johnson]
forecastdate                                                [11/8/16]
state               [U.S., New Mexico, Virginia, Iowa, Wisconsin, ...
startdate           [11/3/2016, 11/1/2016, 11/2/2016, 11/4/2016, 1...
enddate             [11/6/2016, 11/7/2016, 11/5/2016, 11/4/2016, 1...
pollster            [ABC News/Washington Post, Google Consumer Sur...
grade                       [A+, B, A-, B-, A, nan, B+, C+, C-, C, D]
samplesize          [2220.0, 26574.0, 2195.0, 3677.0, 16639.0, 129...
population                                             [lv, rv, a, v]
poll_wt             [8.720654, 7.628472, 6.424334, 6.087135, 5.316...
rawpoll_clinton     [47.0, 38.03, 42.0, 45.0, 48.0, 44.0, 46.0, 41...
rawpoll_trump       [43.0, 35.69, 39.0, 41.0, 44.0, 40.0, 42.7, 46...
rawpoll_johnson     [4.0, 5.46, 6.0, 5.0, 3.0, 7.1, 1.0, 2.0, nan,...
rawpoll_mcmullin    [nan, 24.0, 27.6, 24.52, 25.0, 21.0, 28.0, 30....
adjpoll_clinton     [45.20163, 43.34557, 42.02638, 45.65676, 46.84...
adjpoll_trump       [41.7243, 41.21439, 38.8162, 40.92004, 42.3318...
adjpoll_johnson     [4.626221, 5.175792, 6.844734, 6.069454, 3.726...
adjpoll_mcmullin    [nan, 24.0, 27.70142, 24.13522, 24.52, 25.0, 2...
multiversions                                                [nan, *]
url                 [https://www.washingtonpost.com/news/the-fix/w...
poll_id             [48630, 48847, 48922, 48687, 48848, 48619, 485...
question_id         [76192, 76443, 76636, 76262, 76444, 76163, 760...
createddate         [11/7/16, 11/8/16, 11/6/16, 11/4/16, 11/5/16, ...
timestamp           [09:35:33  8 Nov 2016, 09:24:53  8 Nov 2016, 0...
dtype: object

### ii) checking if the col value are stored with the desired datatypes. esp the 'date' column

In [12]:
pdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12624 entries, 0 to 12623
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cycle             12624 non-null  int64
 1   branch            12624 non-null  object
 2   type              12624 non-null  object
 3   matchup           12624 non-null  object
 4   forecastdate      12624 non-null  object
 5   state             12624 non-null  object
 6   startdate         12624 non-null  object
 7   enddate           12624 non-null  object
 8   pollster          12624 non-null  object
 9   grade             11337 non-null  object
 10  samplesize        12621 non-null  float64
 11  population        12624 non-null  object
 12  poll_wt           12624 non-null  float64
 13  rawpoll_clinton   12624 non-null  float64
 14  rawpoll_trump     12624 non-null  float64
 15  rawpoll_johnson   8397 non-null   float64
 16  rawpoll_mcmullin  90 non-null     float64
 17  adjpoll_clinton   12624 non-null  float64
 18  adjpoll_trump     12624 non-null  float64
 19  adjpoll_johnson   8397 non-null   float64
 20  adjpoll_mcmullin  90 non-null     float64
 21  multiversions     36 non-null     object
 22  url               12621 non-null  object
 23  poll_id           12624 non-null  int64
 24  question_id       12624 non-null  int64
 25  createddate       12624 non-null  object
 26  timestamp         12624 non-null  object
dtypes: float64(10), int64(3), object(14)
memory usage: 2.6+ MB

##### we can change the data types for these columns into "date" format
##### ['forecastdate','startdate','enddate','createddate','timestamp']

##### iv) checking the values within a col and distribution of each value:

# .value_counts()

In [13]:
pdf.state.value_counts()

state
U.S.                    3318
Florida                  444
North Carolina           375
Pennsylvania             375
Ohio                     345
New Hampshire            336
Nevada                   279
Virginia                 273
Michigan                 258
Wisconsin                240
Georgia                  240
Colorado                 240
Arizona                  237
California               213
Iowa                     210
Missouri                 204
Utah                     198
New York                 189
Illinois                 180
Texas                    174
Indiana                  168
New Jersey               162
Oregon                   162
Maine                    159
South Carolina           156
Washington               153
Massachusetts            153
New Mexico               153
Kansas                   153
Louisiana                150
Kentucky                 147
Idaho                    144
Minnesota                144
Maryland                 141
West Virginia            141
Tennessee                138
Arkansas                 135
Oklahoma                 132
Connecticut              132
Alabama                  129
Mississippi              129
Nebraska                 126
Montana                  123
Delaware                 120
Alaska                   114
South Dakota             111
Vermont                  105
North Dakota              93
Rhode Island              87
Wyoming                   87
Hawaii                    84
District of Columbia      78
Maine CD-2                42
Maine CD-1                33
Nebraska CD-2              6
Nebraska CD-3              3
Nebraska CD-1              3
Name: count, dtype: int64

In [14]:
# .value_count() to view it in percentage format
pdf.state.value_counts(normalize=True)

state
U.S.                    0.262833
Florida                 0.035171
North Carolina          0.029705
Pennsylvania            0.029705
Ohio                    0.027329
New Hampshire           0.026616
Nevada                  0.022101
Virginia                0.021625
Michigan                0.020437
Wisconsin               0.019011
Georgia                 0.019011
Colorado                0.019011
Arizona                 0.018774
California              0.016873
Iowa                    0.016635
Missouri                0.016160
Utah                    0.015684
New York                0.014971
Illinois                0.014259
Texas                   0.013783
Indiana                 0.013308
New Jersey              0.012833
Oregon                  0.012833
Maine                   0.012595
South Carolina          0.012357
Washington              0.012120
Massachusetts           0.012120
New Mexico              0.012120
Kansas                  0.012120
Louisiana               0.011882
Kentucky                0.011644
Idaho                   0.011407
Minnesota               0.011407
Maryland                0.011169
West Virginia           0.011169
Tennessee               0.010932
Arkansas                0.010694
Oklahoma                0.010456
Connecticut             0.010456
Alabama                 0.010219
Mississippi             0.010219
Nebraska                0.009981
Montana                 0.009743
Delaware                0.009506
Alaska                  0.009030
South Dakota            0.008793
Vermont                 0.008317
North Dakota            0.007367
Rhode Island            0.006892
Wyoming                 0.006892
Hawaii                  0.006654
District of Columbia    0.006179
Maine CD-2              0.003327
Maine CD-1              0.002614
Nebraska CD-2           0.000475
Nebraska CD-3           0.000238
Nebraska CD-1           0.000238
Name: proportion, dtype: float64

In [15]:
pdf[["state","grade"]].head(10)

        state grade
0        U.S.    A+
1        U.S.     B
2        U.S.    A-
3        U.S.     B
4        U.S.    B-
5        U.S.     A
6        U.S.    A-
7        U.S.    A-
8  New Mexico   NaN
9        U.S.    A-

In [16]:
pdf.groupby(["state","grade"]).aggregate({"grade":"count"})

                 grade
state     grade
Alabama   A-        42
          B         45
          C-        36
Alaska    B         57
          B+         6
...                ...
Wisconsin B-        18
          C-        42
Wyoming   B         45
          B-         3
          C-        36

[321 rows x 1 columns]

In [17]:
pdf[['state','grade']].value_counts()

state          grade
U.S.           A-       1215
               C+        546
               B         162
               C-        126
               A+        114
                        ...
Nebraska CD-1  B           3
Indiana        A           3
Nebraska CD-2  B           3
Missouri       A           3
Mississippi    C           3
Name: count, Length: 321, dtype: int64

In [18]:
pdf.aggregate({"grade":"count"})

grade    11337
dtype: int64

In [19]:
pdf.groupby(["state"])["grade"].value_counts()

state      grade
Alabama    B        45
           A-       42
           C-       36
Alaska     B        57
           C-       36
                    ..
Wisconsin  B+       12
           A+        6
Wyoming    B        45
           C-       36
           B-        3
Name: count, Length: 321, dtype: int64

### dropping columns:

In [20]:
pdf.drop(columns = ['cycle','branch'], inplace = True)

#### renaming columns

In [21]:
# renaming
pdf.rename(columns = {'rawpoll_clinton':'clinton_believers_pc','rawpoll_trump': 'trump_believers_pc','rawpoll_johnson':'johnson_believers_pc','rawpoll_mcmullin':'mcmullin_believers_pc'}, inplace=True)

In [22]:
pdf.columns

Index(['type', 'matchup', 'forecastdate', 'state', 'startdate', 'enddate',
       'pollster', 'grade', 'samplesize', 'population', 'poll_wt',
       'clinton_believers_pc', 'trump_believers_pc', 'johnson_believers_pc',
       'mcmullin_believers_pc', 'adjpoll_clinton', 'adjpoll_trump',
       'adjpoll_johnson', 'adjpoll_mcmullin', 'multiversions', 'url',
       'poll_id', 'question_id', 'createddate', 'timestamp'],
      dtype='object')

#### vii) change the datatypes
##### we can change the data types for these columns into "date" format
##### ['forecastdate','startdate','enddate','createddate','timestamp']

In [23]:
# method 1
date_cols = ['forecastdate','startdate','enddate','createddate','timestamp']

In [24]:
pdf[date_cols] = pdf[date_cols].apply(pd.to_datetime)

C:\Users\sthaa\AppData\Local\Temp\ipykernel_7356\294534771.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pdf[date_cols] = pdf[date_cols].apply(pd.to_datetime)

In [25]:
pdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12624 entries, 0 to 12623
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   type                   12624 non-null  object
 1   matchup                12624 non-null  object
 2   forecastdate           12624 non-null  datetime64[ns]
 3   state                  12624 non-null  object
 4   startdate              12624 non-null  datetime64[ns]
 5   enddate                12624 non-null  datetime64[ns]
 6   pollster               12624 non-null  object
 7   grade                  11337 non-null  object
 8   samplesize             12621 non-null  float64
 9   population             12624 non-null  object
 10  poll_wt                12624 non-null  float64
 11  clinton_believers_pc   12624 non-null  float64
 12  trump_believers_pc     12624 non-null  float64
 13  johnson_believers_pc   8397 non-null   float64
 14  mcmullin_believers_pc  90 non-null     float64
 15  adjpoll_clinton        12624 non-null  float64
 16  adjpoll_trump          12624 non-null  float64
 17  adjpoll_johnson        8397 non-null   float64
 18  adjpoll_mcmullin       90 non-null     float64
 19  multiversions          36 non-null     object
 20  url                    12621 non-null  object
 21  poll_id                12624 non-null  int64
 22  question_id            12624 non-null  int64
 23  createddate            12624 non-null  datetime64[ns]
 24  timestamp              12624 non-null  datetime64[ns]
dtypes: datetime64[ns](5), float64(10), int64(2), object(8)
memory usage: 2.4+ MB

In [26]:
pdf[date_cols].head(5)

  forecastdate  startdate    enddate createddate           timestamp
0   2016-11-08 2016-11-03 2016-11-06  2016-11-07 2016-11-08 09:35:33
1   2016-11-08 2016-11-01 2016-11-07  2016-11-07 2016-11-08 09:35:33
2   2016-11-08 2016-11-02 2016-11-06  2016-11-08 2016-11-08 09:35:33
3   2016-11-08 2016-11-04 2016-11-07  2016-11-07 2016-11-08 09:35:33
4   2016-11-08 2016-11-03 2016-11-06  2016-11-07 2016-11-08 09:35:33

In [27]:
#method 2
ppdf = pd.read_csv("polls.csv",parse_dates= date_cols)

C:\Users\sthaa\AppData\Local\Temp\ipykernel_7356\2275584023.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  ppdf = pd.read_csv("polls.csv",parse_dates= date_cols)

In [28]:
ppdf[date_cols].head(5)

  forecastdate  startdate    enddate createddate           timestamp
0   2016-11-08 2016-11-03 2016-11-06  2016-11-07 2016-11-08 09:35:33
1   2016-11-08 2016-11-01 2016-11-07  2016-11-07 2016-11-08 09:35:33
2   2016-11-08 2016-11-02 2016-11-06  2016-11-08 2016-11-08 09:35:33
3   2016-11-08 2016-11-04 2016-11-07  2016-11-07 2016-11-08 09:35:33
4   2016-11-08 2016-11-03 2016-11-06  2016-11-07 2016-11-08 09:35:33